
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    'greeting.morning': 'Good morning',
    'greeting.afternoon': 'Good afternoon',
    'greeting.evening': 'Good evening',
    'greeting.night': 'Good night',
    'search.placeholder': 'What are you looking for?',
    'search.notFound': 'Oops, your book has escaped from us! 😭 The search fell into a book time hole. Maybe it\'s hiding behind the pages of other stories? Let\'s search together again! 📚✨',
    'search.tryAgain': 'Try different keywords or browse our categories',
    'search.books': 'Books',
    'search.authors': 'Authors',
    'search.booksPlaceholder': 'Search for books...',
    'search.authorsPlaceholder': 'Search for authors...',
    'search.authorNotFound': 'Sorry, we couldn\'t find an author with that name! 😔✨',
    'search.authorNotFoundDescription': 'Maybe they\'re just waiting for their moment to shine. Try searching for different names or check out new categories!',
    'search.authorsFound': 'Found Authors',
    'nav.home': 'Home',
    'nav.favorites': 'Favorites',
    'nav.saved': 'Saved',
    'sidebar.theme': 'Theme',
    'sidebar.language': 'Language',
    'sidebar.logout': 'Logout',
    'sidebar.settings': 'Settings',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.welcome': 'Welcome to ReadNest',
    'settings.title': 'App Settings',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark Mode',
    'settings.open': 'Open Settings',
    'settings.version': 'App Version',
    'settings.versionNumber': '1.0.0',
    'settings.earlyVersion': 'This is an early version',
    'editor.bold': 'Bold',
    'editor.italic': 'Italic',
    'editor.underline': 'Underline',
    'editor.strikethrough': 'Strikethrough',
    'editor.color': 'Color',
    'editor.applyColor': 'Apply color',
    'editor.writeSomething': 'Write something here...',
    'editor.formatting': 'Supported formatting',
    'publish.title': 'Publish a book',
    'publish.description': 'Fill in the information about your book and edit the content before publishing.',
    'publish.bookInfo': 'Book Information',
    'publish.bookContent': 'Book Content',
    'publish.bookTitle': 'Book Title',
    'publish.titlePlaceholder': 'Enter book title',
    'publish.author': 'Author',
    'publish.authorPlaceholder': 'Enter author name',
    'publish.coverImage': 'Book Cover',
    'publish.cover': 'Cover',
    'publish.changeCover': 'Change cover',
    'publish.dropImage': 'Drop image here or click to select',
    'publish.selectImage': 'Select image',
    'publish.recommendedSize': 'Recommended size: 800×1200 pixels',
    'publish.content': 'Book Content',
    'publish.cancel': 'Cancel',
    'publish.publish': 'Publish',
    'publish.authors': 'Authors',
    'publish.authorsPlaceholder': 'Enter authors\' names separated by commas',
    'publish.releaseDate': 'Release Date',
    'publish.selectDate': 'Select a date',
    'publish.saveDraft': 'Save Draft',
    'publish.multipleAuthorsHint': 'If the book was written jointly with other authors, list their names separated by commas',
    'profile.title': 'User Profile',
    'profile.information': 'Information',
    'profile.subscriptions': 'Subscriptions',
    'profile.blocked': 'Blocked Users',
    'profile.editProfile': 'Edit Profile',
    'profile.username': 'Username',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.firstNamePlaceholder': 'Enter your first name',
    'profile.lastNamePlaceholder': 'Enter your last name (optional)',
    'profile.changeAvatar': 'Click on the avatar to change it',
    'profile.saveChanges': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.updateSuccess': 'Profile Updated',
    'profile.updateSuccessMessage': 'Your profile has been successfully updated',
    'profile.updateError': 'Error',
    'profile.updateErrorMessage': 'An error occurred while updating your profile',
    'profile.userID': 'User ID',
    'profile.personalInfo': 'Personal Information',
    'profile.privacy': 'Privacy',
    'profile.privacySettings': 'Privacy Settings',
    'profile.privacyDescription': 'Configure the privacy settings for your profile',
    'profile.hideSubscriptions': 'Hide my subscriptions',
    'profile.hideSubscriptionsDescription': 'Other users won\'t be able to see who you\'re subscribed to',
    'profile.allowComments': 'Allow comments on books',
    'profile.allowCommentsDescription': 'Users will be able to leave comments on your books',
    'profile.perBookCommentsSettings': 'Per-book comment settings',
    'profile.perBookCommentsDescription': 'Configure commenting ability for each book separately',
    'profile.noPublishedBooks': 'You don\'t have any published books yet',
    'profile.privacyUpdated': 'Privacy Settings Updated',
    'profile.subscriptionsHidden': 'Your subscriptions are now hidden from other users',
    'profile.subscriptionsVisible': 'Your subscriptions are now visible to other users',
    'profile.privacyUpdateError': 'An error occurred while updating privacy settings',
    'profile.commentsUpdated': 'Comment Settings Updated',
    'profile.commentsEnabled': 'Comments are enabled for all your books',
    'profile.commentsDisabled': 'Comments are disabled for all your books',
    'profile.commentsUpdateError': 'An error occurred while updating comment settings',
    'profile.usernameCopied': 'Username copied',
    'comments.title': 'Comments',
    'comments.placeholder': 'Write a comment...',
    'comments.submit': 'Submit',
    'comments.sending': 'Sending...',
    'comments.noComments': 'No comments yet. Be the first to leave a comment!',
    'comments.added': 'Comment Added',
    'comments.addedMessage': 'Your comment has been successfully added',
    'comments.disabled': 'Comments Disabled',
    'comments.disabledMessage': 'The author has disabled comments for this book',
    'subscriptions.title': 'My Subscriptions',
    'subscriptions.noSubscriptions': 'No Subscriptions',
    'subscriptions.noSubscriptionsDescription': 'You haven\'t subscribed to any authors yet',
    'subscriptions.mutualSubscription': 'Mutual Subscription',
    'subscriptions.notSubscribedBack': 'Not subscribed to you',
    'subscriptions.unsubscribe': 'Unsubscribe',
    'subscriptions.block': 'Block',
    'subscriptions.unsubscribed': 'Unsubscribed',
    'subscriptions.unsubscribedMessage': 'You have unsubscribed from this user',
    'subscriptions.blocked': 'User Blocked',
    'subscriptions.blockedMessage': 'This user has been added to your block list',
    'blocked.title': 'Blocked Users',
    'blocked.noBlockedUsers': 'No Blocked Users',
    'blocked.noBlockedUsersDescription': 'You haven\'t blocked any users yet',
    'blocked.unblock': 'Unblock',
    'blocked.unblocked': 'User Unblocked',
    'blocked.unblockedMessage': 'This user has been removed from your block list',
    'settings.gradientUI': 'Gradient UI',
    'profile.avatarSizeLimit': 'Maximum file size: 10MB',
    'profile.avatarFormats': 'Supported formats: JPEG, PNG, GIF',
    'profile.avatarDimensions': 'Recommended size: 200x200 to 1000x1000 pixels',
    'profile.bio': 'About me',
    'profile.bioPlaceholder': 'Tell something about yourself...',
    'profile.imageTooLarge': 'Avatar size must not exceed 10MB',
    'profile.imageTooLargeTitle': 'Avatar upload error',
  },
  ru: {
    'greeting.morning': 'Доброе утро',
    'greeting.afternoon': 'Добрый день',
    'greeting.evening': 'Добрый вечер',
    'greeting.night': 'Доброй ночи',
    'search.placeholder': 'Что ищем?',
    'search.notFound': 'Увы, твоя книжечка ускользнула от нас! 😭 Поиск попал в книжную яму времени. Может, она прячется за страницами других историй? Давай поищем вместе ещё раз! 📚✨',
    'search.tryAgain': 'Попробуйте другие ключевые слова или просмотрите наши категории',
    'search.books': 'Книги',
    'search.authors': 'Авторы',
    'search.booksPlaceholder': 'Поиск книг...',
    'search.authorsPlaceholder': 'Поиск авторов...',
    'search.authorNotFound': 'К сожалению, мы не нашли автора с таким именем! 😔✨',
    'search.authorNotFoundDescription': 'Возможно, он всего лишь жд��т своего звездного часа. Поищите по другим именам или посмотрите в новых категориях!',
    'search.authorsFound': 'Найденные авторы',
    'nav.home': 'Главная',
    'nav.favorites': 'Избранное',
    'nav.saved': 'Сохраненные',
    'sidebar.theme': 'Тема',
    'sidebar.language': 'Язык',
    'sidebar.logout': 'Выйти',
    'sidebar.settings': 'Настройки',
    'login.username': 'Имя пользователя',
    'login.password': 'Пароль',
    'login.submit': 'Войти',
    'login.welcome': 'Добро пожаловать в ReadNest',
    'settings.title': 'Настройки приложения',
    'settings.appearance': 'Внешний вид',
    'settings.darkMode': 'Темная тема',
    'settings.open': 'Открыть настройки',
    'settings.version': 'Версия приложения',
    'settings.versionNumber': '1.0.0',
    'settings.earlyVersion': 'Это ранняя версия',
    'editor.bold': 'Жирный',
    'editor.italic': 'Курсив',
    'editor.underline': 'Подчеркнутый',
    'editor.strikethrough': 'Зачеркнутый',
    'editor.color': 'Цвет',
    'editor.applyColor': 'Применить цвет',
    'editor.writeSomething': 'Напишите что-нибудь здесь...',
    'editor.formatting': 'Поддерживаемое форматирование',
    'publish.title': 'Опубликовать книгу',
    'publish.description': 'Заполните информацию о вашей книге и отредактируйте содержимое перед публикацией.',
    'publish.bookInfo': 'Информация о книге',
    'publish.bookContent': 'Содержание книги',
    'publish.bookTitle': 'Название книги',
    'publish.titlePlaceholder': 'Введите название книги',
    'publish.author': 'Автор',
    'publish.authorPlaceholder': 'Введите имя автора',
    'publish.coverImage': 'Обложка книги',
    'publish.cover': 'Обложка',
    'publish.changeCover': 'Изменить обложку',
    'publish.dropImage': 'Перетащите изображение сюда или нажмите для выбора',
    'publish.selectImage': 'Выбрать изображение',
    'publish.recommendedSize': 'Рекомендуемый размер: 800×1200 пикселей',
    'publish.content': 'Содержание книги',
    'publish.cancel': 'Отмена',
    'publish.publish': 'Опубликовать',
    'publish.authors': 'Авторы',
    'publish.authorsPlaceholder': 'Введите имена авторов через запятую',
    'publish.releaseDate': 'Дата выхода',
    'publish.selectDate': 'Выберите дату',
    'publish.saveDraft': 'Сохранить черновик',
    'publish.multipleAuthorsHint': 'Если книгу писали совместно с другими авторами, укажите их имена через запятую',
    'profile.title': 'Профиль пользователя',
    'profile.information': 'Информация',
    'profile.subscriptions': 'Подписки',
    'profile.blocked': 'Черный список',
    'profile.editProfile': 'Редактировать профиль',
    'profile.username': 'Имя пользователя',
    'profile.firstName': 'Имя',
    'profile.lastName': 'Фамилия',
    'profile.firstNamePlaceholder': 'Введите ваше имя',
    'profile.lastNamePlaceholder': 'Введите вашу фамилию (по желанию)',
    'profile.changeAvatar': 'Нажмите на аватарку, чтобы изменить',
    'profile.saveChanges': 'Сохранить изменения',
    'profile.saving': 'Сохранение...',
    'profile.updateSuccess': 'Профиль обновлен',
    'profile.updateSuccessMessage': 'Ваш профиль был успешно обновлен',
    'profile.updateError': 'Ошибка',
    'profile.updateErrorMessage': 'Произошла ошибка при обновлении профиля',
    'profile.userID': 'ID пользователя',
    'profile.personalInfo': 'Личная информация',
    'profile.privacy': 'Конфиденциальность',
    'profile.privacySettings': 'Настройки конфиденциальности',
    'profile.privacyDescription': 'Настройте параметры конфиденциальности вашего профиля',
    'profile.hideSubscriptions': 'Скрыть мои подписки',
    'profile.hideSubscriptionsDescription': 'Другие пользователи не смогут видеть, на кого вы подписаны',
    'profile.allowComments': 'Разрешить комментарии к книгам',
    'profile.allowCommentsDescription': 'Пользователи смогут оставлять комментарии к вашим книгам',
    'profile.perBookCommentsSettings': 'Настройки комментариев для отдельных книг',
    'profile.perBookCommentsDescription': 'Настройте возможность комментирования для каждой книги отдельно',
    'profile.noPublishedBooks': 'У вас пока нет опубликованных книг',
    'profile.privacyUpdated': 'Настро��ки конфиденциальности обновлены',
    'profile.subscriptionsHidden': 'Ваши подписки теперь скрыты от других пользователей',
    'profile.subscriptionsVisible': 'Ваши подписки теперь видны другим пользователям',
    'profile.privacyUpdateError': 'Произошла ошибка при обновлении настроек конфиденциальности',
    'profile.commentsUpdated': 'Настройки комментариев обновлены',
    'profile.commentsEnabled': 'Комментарии включены для всех ваших книг',
    'profile.commentsDisabled': 'Комментарии отключены для всех ваших книг',
    'profile.commentsUpdateError': 'Произошла ошибка при обновлении настроек комментариев',
    'profile.usernameCopied': 'Имя пользователя скопировано',
    'comments.title': 'Комментарии',
    'comments.placeholder': 'Напишите комментарий...',
    'comments.submit': 'Отправить',
    'comments.sending': 'Отправка...',
    'comments.noComments': 'Нет комментариев. Будьте первым, кто оставит комментарий!',
    'comments.added': 'Комментарий добавлен',
    'comments.addedMessage': 'Ваш комментарий был успешно добавлен',
    'comments.disabled': 'Комментарии отключены',
    'comments.disabledMessage': 'Автор отключил комментарии для этой книги',
    'subscriptions.title': 'Мои подписки',
    'subscriptions.noSubscriptions': 'Нет подписок',
    'subscriptions.noSubscriptionsDescription': 'Вы еще не подписаны ни на одного автора',
    'subscriptions.mutualSubscription': 'Взаимная подписка',
    'subscriptions.notSubscribedBack': 'Не подписан на вас',
    'subscriptions.unsubscribe': 'Отписаться',
    'subscriptions.block': 'Заблокировать',
    'subscriptions.unsubscribed': 'Отписка выполнена',
    'subscriptions.unsubscribedMessage': 'Вы отписались от этого пользователя',
    'subscriptions.blocked': 'Пользователь заблокирован',
    'subscriptions.blockedMessage': 'Этот пользователь был добавлен в ваш черный список',
    'blocked.title': 'Заблокированные пользователи',
    'blocked.noBlockedUsers': 'Нет заблокированных пользователей',
    'blocked.noBlockedUsersDescription': 'Вы еще не заблокировали ни одного пользователя',
    'blocked.unblock': 'Разблокировать',
    'blocked.unblocked': 'Пользователь разблокирован',
    'blocked.unblockedMessage': 'Этот пользователь был удален из вашего черного списка',
    'settings.gradientUI': 'Градиентный дизайн',
    'profile.avatarSizeLimit': 'Максимальный размер файла: 10МБ',
    'profile.avatarFormats': 'Поддерживаемые форматы: JPEG, PNG, GIF',
    'profile.avatarDimensions': 'Рекомендуемый размер: 200x200 до 1000x1000 пикселей',
    'profile.bio': 'О себе',
    'profile.bioPlaceholder': 'Расскажите что-нибудь о себе...',
    'profile.imageTooLarge': 'Размер аватара не должен превышать 10МБ',
    'profile.imageTooLargeTitle': 'Ошибка загрузки аватара',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Initialize from localStorage or browser language
    const savedLang = localStorage.getItem('readnest-language') as Language | null;
    if (savedLang) return savedLang;
    
    // Default to Russian per requirements
    return 'ru';
  });

  useEffect(() => {
    // Update localStorage when language changes
    localStorage.setItem('readnest-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prevLang => (prevLang === 'en' ? 'ru' : 'en'));
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
